apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  basicAuth:
    removeHeader: false
    secret: authsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
data:
  users:
    Y2VsaWE6JGFwcjEkLi9QemgwV3YkTVhtQ2lHNldqQ1dYRjMubjlLcWlwLwoK